[package]
name = "ergvein-filters"
version = "0.1.0"
authors = ["Anton Gushcha <ncrashed@protonmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
bitcoin = "0.23.0"
golomb-coded-set = "0.1.0"
bitcoin_hashes = "0.9.0"
